repos:
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.4.1
    hooks:
      - id: sqlfluff-lint
        args: ["--dialect", "postgres", "--templater", "dbt"]
        files: \.sql$
        additional_dependencies:
          - sqlfluff-templater-dbt==3.4.1
          - dbt-postgres==1.9.0

      - id: sqlfluff-fix
        args: ["--dialect", "postgres", "--templater", "dbt"]
        files: \.sql$
        additional_dependencies:
          - sqlfluff-templater-dbt==3.4.1
          - dbt-postgres==1.9.0

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: no-commit-to-branch
      args: [--branch, main]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        files: "\\.(py)$"
        args: ["--profile", "black", "--filter-files"]
