name: 'retail_analytics'
version: '1.0.0'

profile: 'retail_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  "dbt_date:time_zone": "Europe/London"
  start_date: "2016-01-01"
  end_date: "2018-12-31"

models:
  retail_analytics:
    +materialized: view
    +schema: analytics
    +tags: ['analytics']
    staging:
      +schema: staging
      +tags: ['staging']
